image: haskell:8

# -----------------------------------------------------------------
# Based on Code from
# https://git.informatik.uni-kiel.de/stu210876/fortprog-haskellception/blob/master/.gitlab-ci.yml
cache:
  paths:
    - cabal-cache


# https://gitlab.com/dxld/cabal-helper/blob/master/.gitlab-ci.yml
before_script:
  - mkdir -p ~/.cabal $(pwd)/cabal-cache/store
  - ln -s $(pwd)/cabal-cache/store ~/.cabal/store
# -----------------------------------------------------------------

stages:
  - build
  - test

stages:
  - build
  - test

cabal-build:
  stage: build
  tags:
    - my-runner
  script:
    - echo "Building"
    - cabal new-update
    - cabal new-build

cabal-test:
  stage: test
  tags:
    - my-runner
  script:
    - echo "Testing"
    - cabal new-update
    - cabal new-test

cabal-lint:
  stage: test
  tags:
    - my-runner
  script:
    - echo "Linting"
    - curl -sSL https://raw.github.com/ndmitchell/hlint/master/misc/run.sh | sh -s .
