image: haskell:8

# https://gitlab.com/dxld/cabal-helper/blob/master/.gitlab-ci.yml
before_script:
  - mkdir -p ~/.cabal /cache/store
  - ln -s /cache/store ~/.cabal/store

stages:
  - build
  - test

cabal-build:
  stage: build
  tags:
    - my-runner
  script:
    - echo "this is building"
    - cabal new-update
    - cabal new-build

cabal-test:
  stage: test
  tags:
    - my-runner
  script:
    - echo "this is testing"
    - cabal new-update
    - cabal new-test
